### ISSUE TITLE
alias-attribut ist leer...

### ISSUE THREAD

**Issue by haendersonfox** [MetaModels/attribute_alias#13]
hallo in die runde,

mit dem aktuellen nightbuild von gestern ist die auswahl bei dem alias-attribut
und bei dem kombinierten werten leider leer... siehe screens...

hat jemand eine idee?

lg.

alex

https://community.contao.org/de/showthread.php?56323-alias-attribute-ist-leer-keine-Auswahl-m%F6glich&p=363688#post363688

**Comment by discordier** [comment]
Schau bitte mal nach ob du die contao-event-bindings installiert hast.
Die waren in der Vergangenheit mal verloren gegangen.

dc-general in beta23 sollte sie wieder mitbringen, im Zweifel also ein composer update machen und nachsehen ob es dann klappt.

**Comment by haendersonfox** [comment]
event-contao-bindings war dabei, ja.

mit dem aktuellen nightly ist der fehler behoben... sehr sch�n, vielen dank.



Am 24.03.2015 um 18:34 schrieb Christian Schiffler:
