### ISSUE TITLE
add static field to use as fixed "prefix"

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_alias#16]
add static field at first to use as fixed "prefix" e.g. wie work with integer values like year or id...

in this time the alias add "id" if we use year 2017 to "id-2017-...." - after this we can use "year-2017-...."

**Comment by discordier** [comment]
Sounds reansonable, yet we should default it to `id-` to stay "compatible" with Contao

**Comment by zonky2** [comment]
e.g. from xtra
```
$strAlias = standardize(strip_tags($replaceEvent->getBuffer()));
if ('' !== $this->get('prefix')) {
    $strAlias = $this->get('prefix') . substr($strAlias, 3);
}
```

**Comment by discordier** [comment]
Remember to check for existence of 'id-' first!

**Comment by zonky2** [comment]
implemented in https://github.com/MetaModels/attribute_alias/pull/19
