### ISSUE TITLE
should alias genereted even though the field isn´t at panel?

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_alias#21]
should be alias generated even though the field isn´t at input mask, if option "force alias" set?

at this time, we must have the field at input mask...

**Comment by richardhj** [comment]
Is it a question? 😄

**Comment by zonky2** [comment]
jess

**Comment by zonky2** [comment]
MM call 26.09.2017: currently the feature is not considered necessary - it is possible to generate the alias without display as an option in future time

**Comment by zonky2** [comment]
worked in MM 2.2 - maybe aslo in MM 2.1
