### ISSUE TITLE
add own alias generating to use integers

### ISSUE THREAD

**Issue by zonky2** [MetaModels/attribute_alias#25]
we should add a checkbox to use the contao alias generating - it´s not possible to use integers at first character - or own MM implementation...

in MM it´s not a problem to generate al URL like /mytype/zxz/art-no/1234-34523.html

**Comment by discordier** [comment]
I'm not sure I understand the last sentence... so do you want to generate numeric aliases or don't you?

**Comment by zonky2** [comment]
yes, I will!

but currently this is not possible with the generation of an alias via contao - contao puts a prefix "id-" in front of it or you have to specify your own prefix like "year-" or "article-".

**Comment by zonky2** [comment]
fixed
