### ISSUE TITLE
Wenn Pflichtfeld, keine Erstgenerierung

### ISSUE THREAD

**Issue by Tastaturberuf** [MetaModels/attribute_alias#4]
Wenn der Alias als Pflichtfeld leer ist, kommt nur die Meldung das man es ausfüllen soll. Ohne Pflichtfeld klappt alles wunderbar. Da der Alias nicht leer sein kann ist das Pflichtfeld eh obsolet, es sollte immer generiert werden wenn es leer ist.

Oder ist das Verhalten gewünscht?

**Comment by Aybee** [comment]
Ich muss mich hier nochmal dran hängen, weil ich da noch ne Kleinigkeit gefunden habe.

Alias aus Textfeld erstellt
- Eindeutiger Wert
- Neuerstellung erzwingen

Eingabemaske
- Pflichtfeld
- Immer speichern

Ich hatte zuerst vergessen ein Alias-Feld anzulegen. Jetzt habe ich schon Datensätze ohne Alias.
- **falsch**: Wenn ich die Datensätze zum Bearbeiten öffne ist das Alias-Feld leer und wird beim Speichern auch nicht aus dem Textfeld generiert. Auch keine Fehlermeldung.
- **richtig**: Wenn ich einen neuen Datensatz anlege, wird der Alias generiert.
- **richtig**: Wenn ich einen alten Datensatz ohne Alias öffne, den letzten buchstaben des Textfeldes entferne und speichere, wird der Alias auch erzeugt.

Jetzt muss ich im Prinzip jeden Datensatz zum Bearbeiten öffnen, den Wert im Textfeld ändern, speichern, wieder zurück ändern und wieder speichern und schließen.

Ist ein ganz simples MetaModel für ne Taxonomie mit nur einem Textfeld und einem Alias.

*dev-tng @ 8ceb31 - 2015-01-29 17:36:33*

**Comment by discordier** [comment]
Das ist nichts was MM abfangen kann, da der Datensatz an sich ja nicht gespeichert wird.
Das faengt der DCG schon ab und somit "weiss" MetaModels gar nicht, dass du speichern wolltest (weil effektiv ja nicht gespeichert wird).

**Comment by Aybee** [comment]
Ah, ich verstehe, also findet vor einer Speicherung eine Prüfung statt, ob sich überhaupt etwas am Datensatz geändert hat. Wenn nicht, wird auch nicht gespeichert.? Und wenn in dem alias Feld z.B. NULL oder sowas drinn stehen würde, dann müsste es doch eigentlich gehen, oder? Na ja, war ja nur ne Ausnahmesituation.

ps *Ich glaube so ein Feature, dass man Aliase neu generieren kann, wurde früher schon mal angefragt. Das würde sich für den Fall anbieten, wenn man die Datensätze aus einer CSV Datei eingespielt hat.*

pps *Ich hatte vor ein paar Tagen auch mal einen Datensatz, wo ich auf Teufel komm raus keinen Alias abgespeichert bekam. Ich habe den dann manuell direkt in die Datenbank eingetragen. Wenn mir das nochmal unterkommt, mache ich aber ein extra Ticket dazu auf.*
