### ISSUE TITLE
Feature: id für Generierung

### ISSUE THREAD

**Issue by Tastaturberuf** [MetaModels/attribute_alias#5]
Ist es möglich das Datenbankfeld id für die Alias-Generierung zu nutzen? Ich hätte gerne Unique-Aliase aber dann immer mit id, nicht nur wenn der alias schon vergeben ist.

**Comment by zonky2** [comment]
inzwischen wird bei der Generierung des Alias ein Zähler angehangen, sofern Alias-Wert schon vorhanden. Das funktioniert nur, wenn der Alias von sich aus generiert wird und nicht bei manueller Eintragung - dann erscheint eine Fehlermeldung, dass der Alias nicht "unique" sei...
